export const AUTHORIZE        = 'deviate-calendar/APPLICATION/AUTHORIZE'
export const AUTHENTICATED    = 'deviate-calendar/APPLICATION/AUTHENTICATED'
export const SHOWSPINNER      = 'deviate-calendar/APPLICATION/SHOWSPINNER'
export const HIDESPINNER      = 'deviate-calendar/APPLICATION/HIDESPINNER'
export const LOADDEVIATIONS   = 'deviate-calendar/APPLICATION/LOADDEVIATIONS'
export const UPDATEDEVIATION  = 'deviate-calendar/APPLICATION/UPDATEDEVIATION'
